config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :buildings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
has_many :buildingables
has_many :users, through: :buildingables

validates :name, :presence => true, format: { with: /\A[a-zA-Z0-9_ ]{2,20}\z/,
            message: 'ne doit contenir que des caractères alpha-numériques'},
            uniqueness: {case_sensitive: false}

validates :description, :presence => true, format: { with: /\A[a-zA-Z0-9_ ]{2,20}\z/,
                        message: 'ne doit contenir que des caractères alpha-numériques'},
                        uniqueness: {case_sensitive: false}
#after_initialize :set_default_building, :if => :new_record?






end

app/models/buildingable.rb
class Buildingable < ApplicationRecord
  belongs_to :user
  belongs_to :building
end

app/models/user.rb
class User < ApplicationRecord
  has_many :buildingables
  has_many :buildings, through: :buildingables

  enum role: [:user, :vip, :admin]



  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :user
  end



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :authenticate_user!
  #after_action :verify_authorized

  def index

    authorize User

    @building = Building.order('buildings.id asc').all


  end

  def show

  @building = Building.find(params[:id])

    authorize Building

  end


  def new


    @building = Building.new

  end

  def edit
    @building = Building.find(params[:id])
    authorize Building

  end


  def create


    authorize Building

    @building = Building.new(secure_params)
    logger.debug "@toto is: #{@building}"


    if @building.save

        redirect_to new_building_path, success: 'Building as been created'
    else
        redirect_to buildings_path

    end

  end



  def update

    @building = Building.find(params[:id])

    authorize Building


    #@user.building_ids = params[:building_id]
    logger.debug "@toto is: #{@toto}"


    if @building.update_attributes(secure_params)

      redirect_to buildings_path, :notice => "Building updated ."
    else
      redirect_to buildings_path, :alert => "Unable to update Building."
   end
  end

  def destroy
    building = Building.find(params[:id])
    authorize Building
    building.destroy
    redirect_to buildings_path, :notice => "Building deleted."

  end


  private

  def secure_params
    params.require(:building).permit(:name, :description)

  end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.includes(:buildings).order('buildings.id asc').all
 
    authorize User
  end

  def show
    @user = User.find(params[:id])

    authorize @user
    @toto = 5
    logger.debug "@toto is: #{@user}"

  end

  def update
    @user = User.find(params[:id])

    authorize @user

    @user.building_ids=(params[:building_id])[:building_id]

    #@user.building_ids = params[:building_id]
    logger.debug "@toto is: #{@toto}"




    if @user.update_attributes(secure_params)

      redirect_to users_path, :notice => "User updated toto."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."

  end

  private

  def secure_params
    params.require(:user).permit(:role)

  end

  def secure_params_building
    params.require(:buildingable).permit(:building_id)

  end


end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/_building.html.erb
<td>
  <%= link_to user.email, user %>
  <%= link_to user.building_id %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>

  <%= form_for(user) do |g| %>
  <%= g.select(:building_id, User.totos.keys.map {|toto| [toto.titleize,toto]}) %>
    <%= g.submit 'Change building', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/buildings/edit.html.erb
<div class="authform">
  <%= form_for @building do |f| %>
    <h3>Edit building</h3>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

     <%= f.submit 'update', :class => 'button right' %>
  <% end %>
</div>

app/views/buildings/index.html.erb
<h3> Gestion des immeubles   </h3> <%= link_to("Create building", new_building_path(),:class => 'btn btn-primary btn-sm') %>

<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
          <% @building.each do |building| %>

            <%= form_for(building) do |f| %>
              <tr>
                <td><%= building.id if building.id %></td>
                <td><%= building.name if building.name %></td>
                <td><%= building.description if building.description%></td>
                <td>
                <%= link_to("Edit building", edit_building_path(building),:class => 'btn btn-info btn-sm')%>
                <%= link_to("Delete building", building_path(building), :data => { :confirm => "Are you sure?" },
                          :method => :delete, :class => 'btn btn-danger btn-sm') %>
                        <%= link_to("Building", building_path(building)) %></td>

              </tr>

            <% end %>
          <% end %>

        </tbody>

  </table>

app/views/buildings/new.html.erb
<div class="authform">
  <%= form_for(@building) do |f| %>
    <h3>New building</h3>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

     <%= f.submit 'new', :class => 'button right' %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="container">
  <hr>
  <footer>
      <div class="row">
          <div class="col-lg-12">
              <p></p>
          </div>
      </div>
  </footer>
</div>
<!-- /.container -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>

<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>

  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
      <ul class="dropdown-menu">
          <li>
              <%= link_to 'Users', users_path %>
          </li>
          <li>
              <%= link_to 'Buildings', buildings_path %>
          </li>
          <li>
              <%= link_to 'Sign up', new_user_registration_path %>
          </li>
      </ul>
  </li>


  <% end %>


<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
        <li>
            <%= link_to 'Services', page_path('services') %>
        </li>
        <li>
            <%= link_to 'Contact', page_path('contact') %>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to '1 Column Portfolio', page_path('portfolio-1-col') %>
                </li>
                <li>
                    <%= link_to '2 Column Portfolio', page_path('portfolio-2-col') %>
                </li>
                <li>
                    <%= link_to '3 Column Portfolio', page_path('portfolio-3-col') %>
                </li>
                <li>
                    <%= link_to '4 Column Portfolio', page_path('portfolio-4-col') %>
                </li>
                <li>
                    <%= link_to 'Single Portfolio Item', page_path('portfolio-item') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Blog Home 1', page_path('blog-home-1') %>
                </li>
                <li>
                    <%= link_to 'Blog Home 2', page_path('blog-home-2') %>
                </li>
                <li>
                    <%= link_to 'Blog Post', page_path('blog-post') %>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Full Width Page', page_path('full-width') %>
                </li>
                <li>
                    <%= link_to 'Sidebar Page', page_path('sidebar') %>
                </li>
                <li>
                    <%= link_to 'FAQ', page_path('faq') %>
                </li>
                <li>
                    <%= link_to '404', page_path('404') %>
                </li>
                <li>
                    <%= link_to 'Pricing Table', page_path('pricing') %>
                </li>
            </ul>
        </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/404.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">

        <div class="col-lg-12">
            <div class="jumbotron">
                <h1><span class="error-404">404</span>
                </h1>
                <p>The page you're looking for could not be found. Here are some helpful links to get you back on track:</p>
                <ul>
                    <li>
                        <%= link_to 'Home', root_path %>
                    </li>
                    <li>
                        <%= link_to 'About', page_path('about') %>
                    </li>
                    <li>
                        <%= link_to 'Services', page_path('services') %>
                    </li>
                    <li>
                        <%= link_to 'Contact', page_path('contact') %>
                    </li>
                    <li>
                        Portfolio
                        <ul>
                            <li>
                              <%= link_to '1 Column Portfolio', page_path('portfolio-1-col') %>
                            </li>
                            <li>
                              <%= link_to '2 Column Portfolio', page_path('portfolio-2-col') %>
                            </li>
                            <li>
                              <%= link_to '3 Column Portfolio', page_path('portfolio-3-col') %>
                            </li>
                            <li>
                              <%= link_to '4 Column Portfolio', page_path('portfolio-4-col') %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Blog
                        <ul>
                            <li>
                              <%= link_to 'Blog Home 1', page_path('blog-home-1') %>
                            </li>
                            <li>
                              <%= link_to 'Blog Home 2', page_path('blog-home-2') %>
                            </li>
                            <li>
                              <%= link_to 'Blog Post', page_path('blog-post') %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        Other Pages
                        <ul>
                            <li>
                              <%= link_to 'Full Width Page', page_path('full-width') %>
                            </li>
                            <li>
                              <%= link_to 'Sidebar Page', page_path('sidebar') %>
                            </li>
                            <li>
                              <%= link_to 'FAQ', page_path('faq') %>
                            </li>
                            <li>
                              <%= link_to '404', page_path('404') %>
                            </li>
                            <li>
                              <%= link_to 'Pricing Table', page_path('pricing') %>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</div>
<!-- /.container -->

app/views/pages/about.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About
                <small>Subheading</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">About</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Intro Content -->
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </div>
        <div class="col-md-6">
            <h2>About Modern Business</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
        </div>
    </div>
    <!-- /.row -->

    <!-- Team Members -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Team</h2>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                <div class="caption">
                    <h3>John Smith<br>
                        <small>Job Title</small>
                    </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- Our Customers -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Customers</h2>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6">
            <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/pages/full-width.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Full Width Page
                <small>Subheading</small>
            </h1>
            <ol class="breadcrumb">
                <li><%= link_to 'Home', root_path %>
                </li>
                <li class="active">Full Width Page</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <p>Most of Start Bootstrap's unstyled templates can be directly integrated into the Modern Business template. You can view all of our unstyled templates on our website at <a href="http://startbootstrap.com/template-categories/unstyled">http://startbootstrap.com/template-categories/unstyled</a>.</p>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

app/views/users/_user0.html.erb
  <div class="authform">
      <table class="table" >



                    <%= form_for(user) do |f| %>
          <div class="form-group" >
            <tr>
                    <td>
                       <%= user.email if user.email %>
                      <%= user.buildings.map(&:name) if user.buildings %>

                    </td>

                    <td>
                        <%= f.label 'Role' %>
                        <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]},{:prompt => 'Select'},{:class => 'form-control'}) %>
                    </td>

                    <td>

                        <%= f.label 'Building' %>
                        <%= collection_select(:building_id, :building_id, Building.all, :id, :name,
                                  {:prompt => 'Select'},{:class => 'form-control'})%>
                    </td>
              </tr>
                <tr>
                    <td><%= f.submit 'Update', :class => 'btn btn-primary' %></td>
                    <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger') %></td>
                    <td><%= link_to("User", user_path(user)) %></td>
              </tr>


             <% end %>
        </div>
               </table>

  </div>

app/views/users/index.html.erb
<h3> Gestion des users</h3>

<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>nom</th>
                <th>email</th>
                <th>Building</th>
                <th>Role</th>
                <th>Change Building</th>
                <th>application</th>
            </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>

            <%= form_for(user) do |f| %>
              <tr>
                <td><%= user.name if user.name %></td>
                <td><%= user.email if user.email %></td>
                <td><%=user.buildings.map(&:name).flatten.join(' ')  if user.buildings%></td>
                <td><%=f.select(:role, User.roles.keys.map {|role| [role.titleize,role]},{:prompt => 'Select'},
                  {:class => 'form-control'}) %></td>
                <td><%= collection_select(:building_id, :building_id, Building.all, :id, :name,
                          {:prompt => 'Select'},{:class => 'form-control'})%></td>
                <td><%= f.submit 'Update', :class => 'btn btn-primary btn-sm' %>
                <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" },
                          :method => :delete, :class => 'btn btn-danger btn-sm') %>
                        <%= link_to("User", user_path(user)) %></td>

              </tr>

            <% end %>
          <% end %>

        </tbody>

  </table>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Immeuble: <%= @user.buildings.map(&:name) if @user.buildings %></p>